name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies for PSL1GHT
      run: |
        sudo apt-get install autoconf automake bison flex gcc libelf-dev make texinfo libncurses5-dev patch python subversion wget zlib1g-dev libtool libtool-bin python-dev bzip2 libgmp3-dev pkg-config g++ libssl-dev   

    - name: Setup PSL1GHT
      run: |
        git clone https://github.com/ProtoByter/ps3toolchain
        cd ps3toolchain
        sudo ./toolchain-sudo.sh

    - name: make
      run: make

    - name: make pkg
      run: make pkg
