name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup PSL1GHT
      run: |
        git clone https://github.com/ProtoByter/ps3toolchain
        cd ps3toolchain
        sudo ./toolchain.sh
    - name: make
      run: make
    - name: make pkg
      run: make pkg
